export const BOARD_COLUMNS = 8
export const BOARD_ROWS = 9
export const MAX_BOARDS = 5
export const CAREER_WORDS = [
    'зарплата',
    'развитие',
    'карьера',
    'баланс',
    'курс',
    'коллеги',
    'отчет',
    'клиент',
    'работа',
    'успех',
    'рост',
    'офис',
    'прогресс',
    'проект',
    'партнёр',
    'компания',
    'доход',
    'премия',
    'оклад',
    'стаж',
    'опыт',
]
export const BREAKFAST_WORDS = [
    'кофе',
    'омлет',
    'каша',
    'сэндвич',
    'авокадо',
    'блин',
    'блинчик',
    'сырник',
    'творог',
    'кофе',
    'сок',
    'йогурт',
    'яйцо',
    'тунец',
    'пашот',
    'бриошь',
    'тост',
    'хлопья',
    'масло',
    'яичница',
    'оладушки',
    'сосиска',
    'вафли',
    'бекон',
    'круассан',
    'глазунья',
    'молоко',
    'овсянка',
    'булка',
    'багет',
]
export const REQUIRED_CAREER_WORDS = CAREER_WORDS.length
export const REQUIRED_BREAKFAST_WORDS = BREAKFAST_WORDS.length
